channels:
  - pytorch
  - nvidia
  - conda-forge

dependencies:
  - python=3.10
  - pip>=22.0
  - pytorch=1.13
  - pytorch-cuda=11.6
  - numpy=1.23
  - scipy=1.9
  - scikit-learn=1.1
  - torchvision=0.14
  - matplotlib=3.6
  - einops
  - tqdm
  - pandas=1.5
  - tensorboard
  - pip:
      - prefetch_generator
      - aim>=3.15, <3.16
      - PyYAML>=6.0, <7.0
      - omegaconf
      - tokenize-rt
      - types-PyYAML
      - typed-argument-parser<1.8.0
  - jupyter
  - ipykernel
  - jq
  - black
  - pylint
  - isort
  - pytest
  - flake8
  - mypy
  - pydocstyle
